#ifndef SQUIRREL_CONST_H
#define SQUIRREL_CONST_H

#define MASTER_ACTOR 100
#define GRID_ACTOR 101
#define SQUIRREL_ACTOR 102
#define INFECTED_SQUIRREL_ACTOR 103
#define NEWBORN_SQUIRREL_ACTOR 104

#define GRID_SHUTDOWN 105
#define GRID_NEW_MONTH 106

#define SQUIRREL_BIRTH 107
#define SQUIRREL_DEATH 108
#define SQUIRREL_INFECTED 109
#define SQUIRREL_ENDING 110

//verbose output
#define SQURL_LOG 0

#endif
