#ifndef SQUIRREL_CONST_H
#define SQUIRREL_CONST_H

#define MASTER_ACTOR 100
#define GRID_ACTOR 101
#define SQUIRREL_ACTOR 102
#define INFECTED_SQUIRREL_ACTOR 103

#define GRID_SHUTDOWN 104
#define GRID_NEW_MONTH 105
#define SQUIRREL_BIRTH_TAG 106

#endif
